# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/tbltechn/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/tbltechn/proprietary/lib/libprotobuf-cpp-full.so:system/lib/libprotobuf-cpp-full.so \
	vendor/samsung/tbltechn/proprietary/lib/libqdutils.so:system/vendor/lib/libqdutils.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libdataitems.so:system/vendor/lib/libdataitems.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/samsung/tbltechn/proprietary/bin/bridgemgrd:system/vendor/bin/bridgemgrd \
    vendor/samsung/tbltechn/proprietary/bin/efsks:system/vendor/bin/efsks \
    vendor/samsung/tbltechn/proprietary/bin/ks:system/vendor/bin/ks \
    vendor/samsung/tbltechn/proprietary/bin/mdm_helper:system/vendor/bin/mdm_helper \
    vendor/samsung/tbltechn/proprietary/bin/mdm_helper_proxy:system/vendor/bin/mdm_helper_proxy \
    vendor/samsung/tbltechn/proprietary/bin/netmgrd:system/vendor/bin/netmgrd \
    vendor/samsung/tbltechn/proprietary/bin/qcks:system/vendor/bin/qcks \
    vendor/samsung/tbltechn/proprietary/bin/qmuxd:system/vendor/bin/qmuxd \
    vendor/samsung/tbltechn/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/tbltechn/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
	vendor/samsung/tbltechn/proprietary/vendor/lib/hw/nfc_nci.apq8084.so:system/vendor/lib/hw/nfc_nci.apq8084.so \
	vendor/samsung/tbltechn/proprietary/vendor/firmware/sec_s3fwrn5_rfreg.bin:vendor/firmware/sec_s3fwrn5_rfreg.bin
